### ISSUE TITLE
About programming problem list

### ISSUE THREAD

**Issue by RodionGork** [adrianN/adrianN.github.io#2]
This page http://adriann.github.io/programming_problems.html mentions "Project Euler" which contains mostly tasks somehow related to number theory, while problems of the list itself are more about "general programming". I dare to suggest having a look at http://www.codeabbey.com resource which is in many ways similar and has also a list of programming exercises but does not give strong math bias to its challenges.

**Comment by adrianN** [comment]
I will add this to the next update
