### ISSUE TITLE
Elementary problem 11 - mathematical notation

### ISSUE THREAD

**Issue by Pharap** [adrianN/adrianN.github.io#7]
I recently stumbled upon the "Simple Programming Problems" page.
I think it's a good idea, but I'm concerned about Elementary Problem 11.

Is there perhaps a way that this could be rewritten so that people who don't understand the mathematical notation used (particularly the capital sigma/summation) could understand it?

**Comment by adrianN** [comment]
Do you have a suggestion for the formulation? I don't know how to describe the summation with natural language without writing a long block of text.

**Comment by Pharap** [comment]
The best I can come up with at the moment is:
> Write a program that computes the sum of an alternating series where each element of the series is an expression of the form `(-1)^k+1/2k-1` for each value of `k` from `1` to `10^6`, multiplied by 4.

I suspect someone might still have to look up what 'alternating series' means, but the rest might be more understandable. I toyed with using 'fraction' rather than 'expression', but I suspect that might cause some people confusion or send them down the wrong path (e.g. trying to somehow sum fractions rather than simply performing the division to get a decimal value).

**Comment by adrianN** [comment]
Sounds good. I'll incorporate that in the coming days, unless you want to file a PR so that I just have to click merge :)
